env:
  contexts:
    - name: active-haldusjuht
      urls:
        - http://localhost:5032
      includePaths:
        - http://localhost:5032.*
      excludePaths:
        - ^http://localhost:5032/swagger/.*$
        - ^https?://(?!localhost:5032).*$
      authentication:
        method: json
        parameters:
          loginPageUrl: http://localhost:5174/
          loginRequestUrl: http://localhost:5032/api/v1/identity/Account/Login
          loginRequestBody: '{"email":"{%username%}","password":"{%password%}"}'
        verification:
          method: response
          loggedInRegex: '"userId"\s*:\s*"'
          loggedOutRegex: 'User/Password problem'
      sessionManagement:
        method: cookie
      users:
        - name: haldusjuht-user
          credentials:
            username: haldusjuht@puksiir.ee
            password: CeoDev123!
  parameters:
    failOnError: false
    progressToStdout: true

jobs:
  - type: openapi
    parameters:
      apiFile: /Users/kaisaliiv/Projects/puksiir2026-security-tests/swagger.json
      targetUrl: http://localhost:5032

  - type: spider
    parameters:
      context: active-haldusjuht
      user: haldusjuht-user
      url: http://localhost:5032/api/v1
      maxDuration: 5

  - type: passiveScan-config
    parameters:
      enableTags: false
      maxAlertsPerRule: 20
      scanOnlyInScope: true

  - type: activeScan-config
    parameters:
      defaultPolicy: Default Policy
      maxRuleDurationInMins: 2
      maxScanDurationInMins: 20

  - type: activeScan
    parameters:
      context: active-haldusjuht
      user: haldusjuht-user
      url: http://localhost:5032/api/v1

  - type: passiveScan-wait
    parameters:
      maxDuration: 10

  - type: outputSummary
    parameters:
      format: Long
      summaryFile: /Users/kaisaliiv/Desktop/Lõputöö/testing/towing-company/dast/reports/active-haldusjuht-summary.json

  - type: report
    parameters:
      template: traditional-html
      reportDir: /Users/kaisaliiv/Desktop/Lõputöö/testing/towing-company/dast/reports
      reportFile: active-haldusjuht-report.html
      reportTitle: Puksiir ZAP Active Scan (Haldusjuht - A01/IDOR)

  - type: report
    parameters:
      template: traditional-json
      reportDir: /Users/kaisaliiv/Desktop/Lõputöö/testing/towing-company/dast/reports
      reportFile: active-haldusjuht-report.json
      reportTitle: Puksiir ZAP Active Scan (Haldusjuht - A01/IDOR) JSON
